import { Dataset, Algorithm, PerformanceMetrics, Job, NetworkData } from './types';

export const mockDatasets: Dataset[] = [
  {
    id: 'ds1',
    name: 'hESC',
    organism: 'Human',
    type: 'scRNA-seq',
    genes: 1500,
    cells: 758,
    edges: 1250,
    lastUpdated: '2025-12-15',
    description: 'Human embryonic stem cells single-cell RNA-seq dataset'
  },
  {
    id: 'ds2',
    name: 'mDC',
    organism: 'Mouse',
    type: 'scRNA-seq',
    genes: 1833,
    cells: 383,
    edges: 1543,
    lastUpdated: '2025-12-10',
    description: 'Mouse dendritic cells differentiation time series'
  },
  {
    id: 'ds3',
    name: 'HSC',
    organism: 'Mouse',
    type: 'scRNA-seq',
    genes: 2126,
    cells: 1095,
    edges: 1802,
    lastUpdated: '2025-12-08',
    description: 'Hematopoietic stem cell differentiation'
  },
  {
    id: 'ds4',
    name: 'DREAM',
    organism: 'Yeast',
    type: 'bulk RNA-seq',
    genes: 2500,
    cells: 0,
    edges: 3200,
    lastUpdated: '2025-11-28',
    description: 'DREAM challenge yeast dataset'
  },
  {
    id: 'ds5',
    name: 'GeneNetWeaver',
    organism: 'Synthetic',
    type: 'synthetic',
    genes: 1000,
    cells: 500,
    edges: 800,
    lastUpdated: '2025-12-01',
    description: 'Synthetic network generated by GeneNetWeaver'
  },
  {
    id: 'ds6',
    name: 'mESC',
    organism: 'Mouse',
    type: 'scRNA-seq',
    genes: 1987,
    cells: 933,
    edges: 1667,
    lastUpdated: '2025-12-05',
    description: 'Mouse embryonic stem cell differentiation'
  }
];

export const mockAlgorithms: Algorithm[] = [
  {
    id: 'alg1',
    name: 'GENIE3',
    version: '1.0',
    description: 'Random forest-based gene regulatory network inference',
    category: 'Ensemble'
  },
  {
    id: 'alg2',
    name: 'PIDC',
    version: '2.1',
    description: 'Partial Information Decomposition and Context',
    category: 'Information Theory'
  },
  {
    id: 'alg3',
    name: 'GRNBoost2',
    version: '0.7.1',
    description: 'Gradient boosting for network inference',
    category: 'Ensemble'
  },
  {
    id: 'alg4',
    name: 'PPCOR',
    version: '1.0',
    description: 'Partial correlation based network inference',
    category: 'Correlation'
  },
  {
    id: 'alg5',
    name: 'SINCERITIES',
    version: '1.5',
    description: 'Temporally informed network inference',
    category: 'Time Series'
  },
  {
    id: 'alg6',
    name: 'LEAP',
    version: '1.2',
    description: 'Lag-based Expression Association for Pseudotime-series',
    category: 'Time Series'
  },
  {
    id: 'alg7',
    name: 'SCENIC',
    version: '1.1.3',
    description: 'Single-cell regulatory network inference',
    category: 'Single Cell'
  },
  {
    id: 'alg8',
    name: 'GRNVBEM',
    version: '1.0',
    description: 'Variational Bayesian EM for network inference',
    category: 'Bayesian'
  }
];

export const mockPerformanceMetrics: PerformanceMetrics[] = [
  {
    algorithmId: 'alg1',
    algorithmName: 'GENIE3',
    precision: 0.68,
    recall: 0.72,
    f1Score: 0.70,
    auroc: 0.82,
    auprc: 0.75,
    earlyPrecision: 0.65,
    runtime: 125.4,
    memoryUsage: 2048
  },
  {
    algorithmId: 'alg2',
    algorithmName: 'PIDC',
    precision: 0.71,
    recall: 0.68,
    f1Score: 0.69,
    auroc: 0.80,
    auprc: 0.73,
    earlyPrecision: 0.70,
    runtime: 98.2,
    memoryUsage: 1536
  },
  {
    algorithmId: 'alg3',
    algorithmName: 'GRNBoost2',
    precision: 0.74,
    recall: 0.76,
    f1Score: 0.75,
    auroc: 0.85,
    auprc: 0.78,
    earlyPrecision: 0.72,
    runtime: 87.6,
    memoryUsage: 1792
  },
  {
    algorithmId: 'alg4',
    algorithmName: 'PPCOR',
    precision: 0.62,
    recall: 0.65,
    f1Score: 0.63,
    auroc: 0.74,
    auprc: 0.68,
    earlyPrecision: 0.58,
    runtime: 156.8,
    memoryUsage: 2560
  },
  {
    algorithmId: 'alg5',
    algorithmName: 'SINCERITIES',
    precision: 0.66,
    recall: 0.70,
    f1Score: 0.68,
    auroc: 0.78,
    auprc: 0.71,
    earlyPrecision: 0.63,
    runtime: 198.5,
    memoryUsage: 3072
  },
  {
    algorithmId: 'alg6',
    algorithmName: 'LEAP',
    precision: 0.69,
    recall: 0.73,
    f1Score: 0.71,
    auroc: 0.81,
    auprc: 0.74,
    earlyPrecision: 0.67,
    runtime: 143.2,
    memoryUsage: 2304
  },
  {
    algorithmId: 'alg7',
    algorithmName: 'SCENIC',
    precision: 0.70,
    recall: 0.69,
    f1Score: 0.69,
    auroc: 0.79,
    auprc: 0.72,
    earlyPrecision: 0.68,
    runtime: 215.7,
    memoryUsage: 3328
  },
  {
    algorithmId: 'alg8',
    algorithmName: 'GRNVBEM',
    precision: 0.65,
    recall: 0.67,
    f1Score: 0.66,
    auroc: 0.76,
    auprc: 0.69,
    earlyPrecision: 0.61,
    runtime: 178.3,
    memoryUsage: 2816
  }
];

export const mockJobs: Job[] = [
  {
    id: 'job1',
    datasetId: 'ds1',
    datasetName: 'hESC',
    algorithmId: 'alg3',
    algorithmName: 'GRNBoost2',
    status: 'completed',
    progress: 100,
    startTime: '2025-12-20T10:30:00',
    endTime: '2025-12-20T10:31:27'
  },
  {
    id: 'job2',
    datasetId: 'ds2',
    datasetName: 'mDC',
    algorithmId: 'alg1',
    algorithmName: 'GENIE3',
    status: 'running',
    progress: 67,
    startTime: '2025-12-20T11:15:00'
  },
  {
    id: 'job3',
    datasetId: 'ds3',
    datasetName: 'HSC',
    algorithmId: 'alg7',
    algorithmName: 'SCENIC',
    status: 'pending',
    progress: 0,
    startTime: '2025-12-20T11:30:00'
  },
  {
    id: 'job4',
    datasetId: 'ds4',
    datasetName: 'DREAM',
    algorithmId: 'alg2',
    algorithmName: 'PIDC',
    status: 'failed',
    progress: 45,
    startTime: '2025-12-20T09:45:00',
    endTime: '2025-12-20T09:50:12',
    error: 'Memory allocation failed: insufficient resources'
  }
];

export const mockNetworkData: NetworkData = {
  nodes: [
    { id: 'GENE1', label: 'NANOG', score: 0.95 },
    { id: 'GENE2', label: 'OCT4', score: 0.92 },
    { id: 'GENE3', label: 'SOX2', score: 0.89 },
    { id: 'GENE4', label: 'KLF4', score: 0.85 },
    { id: 'GENE5', label: 'MYC', score: 0.82 },
    { id: 'GENE6', label: 'ESRRB', score: 0.78 },
    { id: 'GENE7', label: 'TBX3', score: 0.75 },
    { id: 'GENE8', label: 'ZFP42', score: 0.72 },
    { id: 'GENE9', label: 'STAT3', score: 0.70 },
    { id: 'GENE10', label: 'PRDM14', score: 0.68 }
  ],
  edges: [
    { source: 'GENE1', target: 'GENE2', weight: 0.9, type: 'activation' },
    { source: 'GENE1', target: 'GENE3', weight: 0.85, type: 'activation' },
    { source: 'GENE2', target: 'GENE3', weight: 0.82, type: 'activation' },
    { source: 'GENE3', target: 'GENE4', weight: 0.78, type: 'activation' },
    { source: 'GENE2', target: 'GENE5', weight: 0.75, type: 'repression' },
    { source: 'GENE4', target: 'GENE6', weight: 0.72, type: 'activation' },
    { source: 'GENE5', target: 'GENE7', weight: 0.68, type: 'unknown' },
    { source: 'GENE6', target: 'GENE8', weight: 0.65, type: 'activation' },
    { source: 'GENE7', target: 'GENE9', weight: 0.62, type: 'repression' },
    { source: 'GENE8', target: 'GENE10', weight: 0.58, type: 'activation' },
    { source: 'GENE9', target: 'GENE1', weight: 0.70, type: 'activation' },
    { source: 'GENE10', target: 'GENE4', weight: 0.55, type: 'unknown' }
  ]
};

// Helper functions for generating mock data
export function getAUPRCDistributionData() {
  return mockPerformanceMetrics.map(m => ({
    name: m.algorithmName,
    auprc: m.auprc,
    auroc: m.auroc
  }));
}

export function getPRCurveData(algorithmId: string) {
  // Generate mock Precision-Recall curve data
  const points = [];
  for (let recall = 0; recall <= 1; recall += 0.1) {
    const precision = 0.8 - recall * 0.3 + Math.random() * 0.1;
    points.push({ recall: recall, precision: Math.max(0, Math.min(1, precision)) });
  }
  return points;
}

export function getROCCurveData(algorithmId: string) {
  // Generate mock ROC curve data
  const points = [];
  for (let fpr = 0; fpr <= 1; fpr += 0.1) {
    const tpr = fpr + 0.2 + Math.random() * 0.1;
    points.push({ fpr: fpr, tpr: Math.min(1, tpr) });
  }
  return points;
}
